name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     - name: Checkout
       uses: actions/checkout@v4

     - name: Install dependencies
       run: sudo apt update && sudo apt install -y libreadline-dev

     - name: Build
       run: make
